name: 'pardot'
version: '1.2.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<3.0.0"]
models:
  pardot:
    +materialized: table
    +schema: pardot
    intermediate:
      +materialized: ephemeral
    staging:
      +schema: stg_pardot
vars:
  pardot:
    campaign: "{{ source('pardot', 'campaign') }}"
    list_membership: "{{ source('pardot', 'list_membership') }}"
    list: "{{ source('pardot', 'list') }}"
    opportunity_prospect: "{{ source('pardot', 'opportunity_prospect') }}"
    opportunity: "{{ source('pardot', 'opportunity') }}"
    prospect: "{{ source('pardot', 'prospect') }}"
    visitor_activity: "{{ source('pardot', 'visitor_activity') }}"
    visitor: "{{ source('pardot', 'visitor') }}"
    prospect_metrics_activity_types: []
    prospect_passthrough_columns: []
